#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Apr 06, 2019 03:34:56 PM IST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ER_support

def vp_start_gui(fedd):
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    ER_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    ER_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("990x716+1973+14")
        top.title("Energy Router")
        top.configure(background="#ccd8cb")
        top.configure(highlightcolor="black")

        self.Feedback_frame = tk.Frame(top)
        self.Feedback_frame.place(relx=0.03, rely=0.042, relheight=0.468
                , relwidth=0.82)
        self.Feedback_frame.configure(relief='groove')
        self.Feedback_frame.configure(borderwidth="2")
        self.Feedback_frame.configure(relief="groove")
        self.Feedback_frame.configure(width=815)

        self.slave32 = tk.LabelFrame(self.Feedback_frame)
        self.slave32.place(relx=0.012, rely=0.03, relheight=0.94, relwidth=0.185)

        self.slave32.configure(relief='groove')
        self.slave32.configure(text='''0X32''')
        self.slave32.configure(width=150)

        self.Label1_9 = tk.Label(self.slave32)
        self.Label1_9.place(relx=0.267, rely=0.095, height=18, width=55
                , bordermode='ignore')
        self.Label1_9.configure(activebackground="#f9f9f9")
        self.Label1_9.configure(text='''PORT - 1''')

        self.Label1_10 = tk.Label(self.slave32)
        self.Label1_10.place(relx=0.267, rely=0.54, height=18, width=55
                , bordermode='ignore')
        self.Label1_10.configure(activebackground="#f9f9f9")
        self.Label1_10.configure(text='''PORT - 2''')

        self.voltage_port1_label_32 = tk.Label(self.slave32)
        self.voltage_port1_label_32.place(relx=0.133, rely=0.222, height=18
                , width=64, bordermode='ignore')
        self.voltage_port1_label_32.configure(activebackground="#f9f9f9")
        self.voltage_port1_label_32.configure(text='''VOLTAGE:''')

        self.current_port1_label_32 = tk.Label(self.slave32)
        self.current_port1_label_32.place(relx=0.133, rely=0.317, height=18
                , width=65, bordermode='ignore')
        self.current_port1_label_32.configure(activebackground="#f9f9f9")
        self.current_port1_label_32.configure(text='''CURRENT:''')

        self.current_port2_label = tk.Label(self.slave32)
        self.current_port2_label.place(relx=0.133, rely=0.762, height=18
                , width=65, bordermode='ignore')
        self.current_port2_label.configure(activebackground="#f9f9f9")
        self.current_port2_label.configure(text='''CURRENT:''')

        self.voltage_port2_label = tk.Label(self.slave32)
        self.voltage_port2_label.place(relx=0.133, rely=0.667, height=18
                , width=64, bordermode='ignore')
        self.voltage_port2_label.configure(activebackground="#f9f9f9")
        self.voltage_port2_label.configure(text='''VOLTAGE:''')

        self.voltage_port1_value_32 = tk.Label(self.slave32)
        self.voltage_port1_value_32.place(relx=0.6, rely=0.222, height=18
                , width=36, bordermode='ignore')
        self.voltage_port1_value_32.configure(activebackground="#f9f9f9")
        self.voltage_port1_value_32.configure(text='''Label''')

        self.current_port1_value_32 = tk.Label(self.slave32)
        self.current_port1_value_32.place(relx=0.6, rely=0.317, height=18
                , width=36, bordermode='ignore')
        self.current_port1_value_32.configure(activebackground="#f9f9f9")
        self.current_port1_value_32.configure(text='''Label''')

        self.voltage_port2_value_32 = tk.Label(self.slave32)
        self.voltage_port2_value_32.place(relx=0.6, rely=0.667, height=18
                , width=36, bordermode='ignore')
        self.voltage_port2_value_32.configure(activebackground="#f9f9f9")
        self.voltage_port2_value_32.configure(text='''Label''')

        self.current_port2_value_32 = tk.Label(self.slave32)
        self.current_port2_value_32.place(relx=0.6, rely=0.762, height=18
                , width=36, bordermode='ignore')
        self.current_port2_value_32.configure(activebackground="#f9f9f9")
        self.current_port2_value_32.configure(text='''Label''')

        self.slave33 = tk.LabelFrame(self.Feedback_frame)
        self.slave33.place(relx=0.209, rely=0.03, relheight=0.94, relwidth=0.185)

        self.slave33.configure(relief='groove')
        self.slave33.configure(text='''0X33''')
        self.slave33.configure(width=150)

        self.Label1_5 = tk.Label(self.slave33)
        self.Label1_5.place(relx=0.333, rely=0.095, height=18, width=55
                , bordermode='ignore')
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(text='''PORT - 1''')

        self.Label1_12 = tk.Label(self.slave33)
        self.Label1_12.place(relx=0.333, rely=0.54, height=18, width=55
                , bordermode='ignore')
        self.Label1_12.configure(activebackground="#f9f9f9")
        self.Label1_12.configure(text='''PORT - 2''')

        self.voltage_port1_label_33 = tk.Label(self.slave33)
        self.voltage_port1_label_33.place(relx=0.133, rely=0.222, height=18
                , width=64, bordermode='ignore')
        self.voltage_port1_label_33.configure(activebackground="#f9f9f9")
        self.voltage_port1_label_33.configure(text='''VOLTAGE:''')

        self.Label2_16 = tk.Label(self.slave33)
        self.Label2_16.place(relx=0.133, rely=0.317, height=18, width=65
                , bordermode='ignore')
        self.Label2_16.configure(activebackground="#f9f9f9")
        self.Label2_16.configure(text='''CURRENT:''')

        self.Label2_22 = tk.Label(self.slave33)
        self.Label2_22.place(relx=0.133, rely=0.762, height=18, width=65
                , bordermode='ignore')
        self.Label2_22.configure(activebackground="#f9f9f9")
        self.Label2_22.configure(text='''CURRENT:''')

        self.voltage_port2_label_33 = tk.Label(self.slave33)
        self.voltage_port2_label_33.place(relx=0.133, rely=0.667, height=18
                , width=64, bordermode='ignore')
        self.voltage_port2_label_33.configure(activebackground="#f9f9f9")
        self.voltage_port2_label_33.configure(text='''VOLTAGE:''')

        self.voltage_port1_value_33 = tk.Label(self.slave33)
        self.voltage_port1_value_33.place(relx=0.6, rely=0.222, height=18
                , width=36, bordermode='ignore')
        self.voltage_port1_value_33.configure(text='''Label''')

        self.Label2 = tk.Label(self.slave33)
        self.Label2.place(relx=0.6, rely=0.667, height=18, width=36
                , bordermode='ignore')
        self.Label2.configure(text='''Label''')

        self.Label4 = tk.Label(self.slave33)
        self.Label4.place(relx=0.6, rely=0.317, height=18, width=36
                , bordermode='ignore')
        self.Label4.configure(text='''Label''')

        self.Label5 = tk.Label(self.slave33)
        self.Label5.place(relx=0.6, rely=0.762, height=18, width=36
                , bordermode='ignore')
        self.Label5.configure(text='''Label''')

        self.slave36 = tk.LabelFrame(self.Feedback_frame)
        self.slave36.place(relx=0.8, rely=0.03, relheight=0.94, relwidth=0.185)
        self.slave36.configure(relief='groove')
        self.slave36.configure(text='''0X36''')
        self.slave36.configure(width=150)

        self.Label1_8 = tk.Label(self.slave36)
        self.Label1_8.place(relx=0.267, rely=0.095, height=18, width=55
                , bordermode='ignore')
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(text='''PORT - 1''')

        self.Label1_11 = tk.Label(self.slave36)
        self.Label1_11.place(relx=0.333, rely=0.54, height=18, width=55
                , bordermode='ignore')
        self.Label1_11.configure(activebackground="#f9f9f9")
        self.Label1_11.configure(text='''PORT - 2''')

        self.voltage_port1_label_36 = tk.Label(self.slave36)
        self.voltage_port1_label_36.place(relx=0.133, rely=0.222, height=18
                , width=64, bordermode='ignore')
        self.voltage_port1_label_36.configure(activebackground="#f9f9f9")
        self.voltage_port1_label_36.configure(text='''VOLTAGE:''')

        self.Label2_20 = tk.Label(self.slave36)
        self.Label2_20.place(relx=0.133, rely=0.317, height=18, width=65
                , bordermode='ignore')
        self.Label2_20.configure(activebackground="#f9f9f9")
        self.Label2_20.configure(text='''CURRENT:''')

        self.Label2_25 = tk.Label(self.slave36)
        self.Label2_25.place(relx=0.133, rely=0.762, height=18, width=65
                , bordermode='ignore')
        self.Label2_25.configure(activebackground="#f9f9f9")
        self.Label2_25.configure(text='''CURRENT:''')

        self.voltage_port2_label_36 = tk.Label(self.slave36)
        self.voltage_port2_label_36.place(relx=0.133, rely=0.667, height=18
                , width=64, bordermode='ignore')
        self.voltage_port2_label_36.configure(activebackground="#f9f9f9")
        self.voltage_port2_label_36.configure(text='''VOLTAGE:''')

        self.Label13 = tk.Label(self.slave36)
        self.Label13.place(relx=0.6, rely=0.222, height=18, width=36
                , bordermode='ignore')
        self.Label13.configure(text='''Label''')

        self.Label14 = tk.Label(self.slave36)
        self.Label14.place(relx=0.6, rely=0.667, height=18, width=36
                , bordermode='ignore')
        self.Label14.configure(text='''Label''')

        self.Label15 = tk.Label(self.slave36)
        self.Label15.place(relx=0.6, rely=0.762, height=18, width=36
                , bordermode='ignore')
        self.Label15.configure(text='''Label''')

        self.Label16 = tk.Label(self.slave36)
        self.Label16.place(relx=0.6, rely=0.317, height=18, width=36
                , bordermode='ignore')
        self.Label16.configure(text='''Label''')

        self.slave35 = tk.LabelFrame(self.Feedback_frame)
        self.slave35.place(relx=0.603, rely=0.03, relheight=0.94, relwidth=0.185)

        self.slave35.configure(relief='groove')
        self.slave35.configure(text='''0X35''')
        self.slave35.configure(width=150)

        self.Label1_7 = tk.Label(self.slave35)
        self.Label1_7.place(relx=0.267, rely=0.095, height=18, width=55
                , bordermode='ignore')
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(text='''PORT - 1''')

        self.Label1_1 = tk.Label(self.slave35)
        self.Label1_1.place(relx=0.333, rely=0.54, height=18, width=55
                , bordermode='ignore')
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(text='''PORT - 2''')

        self.voltage_port1_label_35 = tk.Label(self.slave35)
        self.voltage_port1_label_35.place(relx=0.133, rely=0.222, height=18
                , width=64, bordermode='ignore')
        self.voltage_port1_label_35.configure(activebackground="#f9f9f9")
        self.voltage_port1_label_35.configure(text='''VOLTAGE:''')

        self.Label2_19 = tk.Label(self.slave35)
        self.Label2_19.place(relx=0.133, rely=0.317, height=18, width=65
                , bordermode='ignore')
        self.Label2_19.configure(activebackground="#f9f9f9")
        self.Label2_19.configure(text='''CURRENT:''')

        self.Label2_24 = tk.Label(self.slave35)
        self.Label2_24.place(relx=0.133, rely=0.762, height=18, width=65
                , bordermode='ignore')
        self.Label2_24.configure(activebackground="#f9f9f9")
        self.Label2_24.configure(text='''CURRENT:''')

        self.voltage_port2_label_35 = tk.Label(self.slave35)
        self.voltage_port2_label_35.place(relx=0.133, rely=0.667, height=18
                , width=64, bordermode='ignore')
        self.voltage_port2_label_35.configure(activebackground="#f9f9f9")
        self.voltage_port2_label_35.configure(text='''VOLTAGE:''')

        self.Label9 = tk.Label(self.slave35)
        self.Label9.place(relx=0.6, rely=0.222, height=18, width=36
                , bordermode='ignore')
        self.Label9.configure(text='''Label''')

        self.Label10 = tk.Label(self.slave35)
        self.Label10.place(relx=0.6, rely=0.317, height=18, width=36
                , bordermode='ignore')
        self.Label10.configure(text='''Label''')

        self.Label11 = tk.Label(self.slave35)
        self.Label11.place(relx=0.6, rely=0.667, height=18, width=36
                , bordermode='ignore')
        self.Label11.configure(text='''Label''')

        self.Label12 = tk.Label(self.slave35)
        self.Label12.place(relx=0.6, rely=0.762, height=18, width=36
                , bordermode='ignore')
        self.Label12.configure(text='''Label''')

        self.slav34 = tk.LabelFrame(self.Feedback_frame)
        self.slav34.place(relx=0.406, rely=0.03, relheight=0.94, relwidth=0.185)
        self.slav34.configure(relief='groove')
        self.slav34.configure(text='''0X34''')
        self.slav34.configure(width=150)

        self.Label1_6 = tk.Label(self.slav34)
        self.Label1_6.place(relx=0.267, rely=0.095, height=18, width=55
                , bordermode='ignore')
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(text='''PORT - 1''')

        self.Label1_2 = tk.Label(self.slav34)
        self.Label1_2.place(relx=0.333, rely=0.54, height=18, width=55
                , bordermode='ignore')
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(text='''PORT - 2''')

        self.voltage_port1_label_34 = tk.Label(self.slav34)
        self.voltage_port1_label_34.place(relx=0.133, rely=0.222, height=18
                , width=64, bordermode='ignore')
        self.voltage_port1_label_34.configure(activebackground="#f9f9f9")
        self.voltage_port1_label_34.configure(text='''VOLTAGE:''')

        self.Label2_17 = tk.Label(self.slav34)
        self.Label2_17.place(relx=0.133, rely=0.317, height=18, width=65
                , bordermode='ignore')
        self.Label2_17.configure(activebackground="#f9f9f9")
        self.Label2_17.configure(text='''CURRENT:''')

        self.Label2_18 = tk.Label(self.slav34)
        self.Label2_18.place(relx=0.133, rely=0.317, height=18, width=65
                , bordermode='ignore')
        self.Label2_18.configure(activebackground="#f9f9f9")
        self.Label2_18.configure(text='''CURRENT:''')

        self.Label2_23 = tk.Label(self.slav34)
        self.Label2_23.place(relx=0.133, rely=0.762, height=18, width=65
                , bordermode='ignore')
        self.Label2_23.configure(activebackground="#f9f9f9")
        self.Label2_23.configure(text='''CURRENT:''')

        self.voltage_port2_label_34 = tk.Label(self.slav34)
        self.voltage_port2_label_34.place(relx=0.133, rely=0.667, height=18
                , width=64, bordermode='ignore')
        self.voltage_port2_label_34.configure(activebackground="#f9f9f9")
        self.voltage_port2_label_34.configure(text='''VOLTAGE:''')

        self.voltage_port1_value_34 = tk.Label(self.slav34)
        self.voltage_port1_value_34.place(relx=0.6, rely=0.222, height=18
                , width=36, bordermode='ignore')
        self.voltage_port1_value_34.configure(text='''Label''')

        self.Label6 = tk.Label(self.slav34)
        self.Label6.place(relx=0.6, rely=0.317, height=18, width=36
                , bordermode='ignore')
        self.Label6.configure(text='''Label''')

        self.Label7 = tk.Label(self.slav34)
        self.Label7.place(relx=0.6, rely=0.667, height=18, width=36
                , bordermode='ignore')
        self.Label7.configure(text='''Label''')

        self.Label8 = tk.Label(self.slav34)
        self.Label8.place(relx=0.6, rely=0.762, height=18, width=36
                , bordermode='ignore')
        self.Label8.configure(text='''Label''')

if __name__ == '__main__':
    vp_start_gui()





