#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  Apr 21, 2019 12:25:14 PM IST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1261x962+488+47
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr44 \
        -borderwidth 2 -relief groove -width 435 -height 455 
    vTcl:DefineAlias "$top.tFr44" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr44
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font "TkDefaultFont"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_3_0.scr45 \
        -background {#d9d9d9} -height 438 -highlightcolor black -width 410 
    vTcl:DefineAlias "$site_3_0.scr45" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1
        .top42.tFr44.scr45.01 configure -columns {Col1}
        .top42.tFr44.scr45.01 heading #0 -text Tree
        .top42.tFr44.scr45.01 heading #0 -anchor center
        .top42.tFr44.scr45.01 column #0 -width 198
        .top42.tFr44.scr45.01 column #0 -minwidth 20
        .top42.tFr44.scr45.01 column #0 -stretch 1
        .top42.tFr44.scr45.01 column #0 -anchor w
        .top42.tFr44.scr45.01 heading Col1 -text Col1
        .top42.tFr44.scr45.01 heading Col1 -anchor center
        .top42.tFr44.scr45.01 column Col1 -width 198
        .top42.tFr44.scr45.01 column Col1 -minwidth 20
        .top42.tFr44.scr45.01 column Col1 -stretch 1
        .top42.tFr44.scr45.01 column Col1 -anchor w
    place $site_3_0.scr45 \
        -in $site_3_0 -x 10 -y 10 -width 410 -relwidth 0 -height 438 \
        -relheight 0 -anchor nw -bordermode ignore 
    set site_3_0 $top.m46
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr47 \
        -borderwidth 2 -relief groove -width 525 -height 455 
    vTcl:DefineAlias "$top.tFr47" "TFrame1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr47
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font "TkDefaultFont"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_3_0.scr45 \
        -background {#d9d9d9} -height 428 -highlightcolor black -width 500 
    vTcl:DefineAlias "$site_3_0.scr45" "Scrolledtreeview1_2" vTcl:WidgetProc "Toplevel1" 1
        .top42.tFr47.scr45.01 configure -columns {Col1}
        .top42.tFr47.scr45.01 heading #0 -text Tree
        .top42.tFr47.scr45.01 heading #0 -anchor center
        .top42.tFr47.scr45.01 column #0 -width 243
        .top42.tFr47.scr45.01 column #0 -minwidth 20
        .top42.tFr47.scr45.01 column #0 -stretch 1
        .top42.tFr47.scr45.01 column #0 -anchor w
        .top42.tFr47.scr45.01 heading Col1 -text Col1
        .top42.tFr47.scr45.01 heading Col1 -anchor center
        .top42.tFr47.scr45.01 column Col1 -width 243
        .top42.tFr47.scr45.01 column Col1 -minwidth 20
        .top42.tFr47.scr45.01 column Col1 -stretch 1
        .top42.tFr47.scr45.01 column Col1 -anchor w
    place $site_3_0.scr45 \
        -in $site_3_0 -x 10 -y 10 -width 500 -relwidth 0 -height 428 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr48 \
        -borderwidth 2 -relief groove -width 985 -height 305 
    vTcl:DefineAlias "$top.tFr48" "TFrame1_3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr48
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font "TkDefaultFont"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_3_0.scr45 \
        -background {#d9d9d9} -height 15 -highlightcolor black -width 30 
    vTcl:DefineAlias "$site_3_0.scr45" "Scrolledtreeview1_4" vTcl:WidgetProc "Toplevel1" 1
        .top42.tFr48.scr45.01 configure -columns {Col1}
        .top42.tFr48.scr45.01 heading #0 -text Tree
        .top42.tFr48.scr45.01 heading #0 -anchor center
        .top42.tFr48.scr45.01 column #0 -width 473
        .top42.tFr48.scr45.01 column #0 -minwidth 20
        .top42.tFr48.scr45.01 column #0 -stretch 1
        .top42.tFr48.scr45.01 column #0 -anchor w
        .top42.tFr48.scr45.01 heading Col1 -text Col1
        .top42.tFr48.scr45.01 heading Col1 -anchor center
        .top42.tFr48.scr45.01 column Col1 -width 473
        .top42.tFr48.scr45.01 column Col1 -minwidth 20
        .top42.tFr48.scr45.01 column Col1 -stretch 1
        .top42.tFr48.scr45.01 column Col1 -anchor w
    place $site_3_0.scr45 \
        -in $site_3_0 -x 10 -y 10 -width 960 -relwidth 0 -height 288 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab43 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -text Label 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab44" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab45" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr44 \
        -in $top -x 80 -y 90 -width 435 -relwidth 0 -height 455 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr47 \
        -in $top -x 660 -y 90 -width 525 -relwidth 0 -height 455 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr48 \
        -in $top -x 130 -y 630 -width 985 -relwidth 0 -height 305 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 180 -y 40 -width 206 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 810 -y 40 -width 206 -height 38 -anchor nw \
        -bordermode ignore 
    place $top.lab45 \
        -in $top -x 510 -y 580 -width 206 -height 38 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

